version: '3.3'
services:
  serv1:
#    image: ddsderek/easyimage:latest
    image: repo.local.com/easyimage:2.8.3
    container_name: easyimage
    ports:
      - '8080:80'
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
#    privileged: true
    volumes:
      - '/home/data/easyimage/config:/app/web/config'
      - '/home/data/easyimage/i:/app/web/i'
    restart: unless-stopped


#      'mkdir -p /run/php/ && touch /run/php/php7.4-fpm.pid' #如果报FPM initialization failed错,使用docker exec -it 容器名 bash 执行此命令
