version: '3.3'
services:
  serv1:
#    image: flowable/all-in-one
    image: repo.local.com/flowable-all-in-one:20230903
    container_name: flowable
#    volumes:
#      - /home/data/jellyfin/config:/config
#      - /home/data/jellyfin/cache:/cache
#      - /home/data/jellyfin/media:/media
#    environment:
#      TZ: Asia/Shanghai
#      PUID: 0
#      PGID: 0
#    privileged: true
#    devices:
#直通显卡给 Docker 容器，用于硬解
#      - /dev/dri:/dev/dri
#    extra_hosts:
#      "api.themoviedb.org": "13.224.161.90"
    ports:
      - 8080:8080
    restart:
      unless-stopped
#visit via http:youip:8080/flowale-idm by admin test
