version: '3.3'

#networks:
#  blinko-network:
#    driver: bridge


services:
  serv1:
#    image: corentinth/enclosed
    image: repo.local.com/enclosed:1.16.0
    container_name: enclosed
    volumes:
      - /home/data/enclosed/data:/app/.data
    environment:
      TZ: Asia/Shanghai
#    privileged: true
#    devices:
#直通显卡给 Docker 容器，用于硬解
#      - /dev/dri:/dev/dri
#    extra_hosts:
#      "api.themoviedb.org": "13.224.161.90"
#    network_mode: host
#    command: ['bash','-c','/app/conf/server.toml']
    ports:
      - 8787:8787
    restart:
      unless-stopped

