version: '3.3'

#networks:
#  blinko-network:
#    driver: bridge


services:
  serv1:
#    image: nyanmisaka/jellyfin:latest
    image: repo.local.com/jellyfin:10.8.10
    container_name: jellyfin
#    volumes:
#      - /home/data/jellyfin/config:/config
#    environment:
#      TZ: Asia/Shanghai
#    privileged: true
#    devices:
#直通显卡给 Docker 容器，用于硬解
#      - /dev/dri:/dev/dri
#    extra_hosts:
#      "api.themoviedb.org": "13.224.161.90"
    ports:
      - 8096:8096
    restart:
      unless-stopped

