version: '3.3'

#networks:
#  blinko-network:
#    driver: bridge


services:
  serv1:
#    image: dpanel/dpanel:lite
    image: repo.local.com/dpanel:lite
    container_name: dpanel
    volumes:
      - /home/data/dpanel:/dpanel
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      APP_NAME: dpanel
#    privileged: true
#    devices:
#直通显卡给 Docker 容器，用于硬解
#      - /dev/dri:/dev/dri
#    extra_hosts:
#      "api.themoviedb.org": "13.224.161.90"
#    network_mode: host
#    command: ['bash','-c','/app/conf/server.toml']
    ports:
      - 8091:8080
    restart:
      unless-stopped

