version: '3.3'
services:
  Postgresql:
    image: postgres:14.2
    container_name: pgsql
    user: root
    volumes:
      - /home/data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    privileged: true
    ports:
      - 5432:5432 
    restart:
      always

