version: '3.3'

#networks:
#  blinko-network:
#    driver: bridge


services:
  serv1:
#    image: linzeyi/hivision_idphotos
    image: repo.local.com/hivision_idphotos:1.3.1
    container_name: idphotos
#    volumes:
#      - /home/data/jellyfin/config:/config
#    environment:
#      TZ: Asia/Shanghai
#    privileged: true
#    devices:
#直通显卡给 Docker 容器，用于硬解
#      - /dev/dri:/dev/dri
#    extra_hosts:
#      "api.themoviedb.org": "13.224.161.90"
#    network_mode: host
#    command: ['bash','-c','/app/conf/server.toml']
    ports:
      - 7860:7860
    restart:
      unless-stopped

