services:
  termix:
#    image: ghcr.io/lukegus/termix:latest
    image: registry.cn-hangzhou.aliyuncs.com/sanwenjing/termix:2.0.0
    container_name: termix
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - termix-data:/app/data
    environment:
      PORT: "8080"
    depends_on:
      - guacd
    networks:
      - termix-net

  guacd:
#    image: docker.1ms.run/guacamole/guacd:latest
    image: registry.cn-hangzhou.aliyuncs.com/sanwenjing/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    ports:
      - "4822:4822"
    networks:
      - termix-net

volumes:
  termix-data:
    driver: local

networks:
  termix-net:
    driver: bridge
