version: '3.3'

#networks:
#  blinko-network:
#    driver: bridge


services:
  serv1:
#    image: swr.cn-north-4.myhuaweicloud.com/jeven/jsnes:1.0.0
    image: repo.local.com/jsnes:1.0.0
    container_name: jsnes
#    volumes:
#      - /home/data/jellyfin/config:/config
#    environment:
#      TZ: Asia/Shanghai
#    privileged: true
#    devices:
#直通显卡给 Docker 容器，用于硬解
#      - /dev/dri:/dev/dri
#    extra_hosts:
#      "api.themoviedb.org": "13.224.161.90"
#    network_mode: host
#    command: ['bash','-c','/app/conf/server.toml']
    ports:
      - 8100:80
    restart:
      unless-stopped

