version: '3.3'

services:
  samba:
    image: dperson/samba
    container_name: serv-samba
    restart: always
    network_mode: bridge
    ports:
      - "139:139"
      - "445:445"
    environment:
      USER: "sharedata;123456"
      #<name;/path>[;browse;readonly;guest;users;admins;writelist;comment
      SHARE: "sharedata;/mount/;yes;no;yes;all;all;all"
    volumes:
      - /home/data/samba:/mount



