version: '3.3'
services:
  qinglong:
#    image: whyour/qinglong
    image: repo.local.com/qinglong:2.10.13
    container_name: qinglong
    volumes:
      - /home/data/qinglong/config:/ql/config
      - /home/data/qinglong/log:/ql/log
      - /home/data/qinglong/db:/ql/db
      - /home/data/qinglong/scripts:/ql/scripts
      - /home/data/qinglong/jbot:/ql/jbot
      - /home/data/qinglong/repo:/ql/repo
    environment:
      ENABLE_HANGUP: 'true'
      ENABLE_WEB_PANEL: 'true'
#    privileged: true
    ports:
      - 5700:5700
    restart:
      unless-stopped

