version: '3.3'

#networks:
#  blinko-network:
#    driver: bridge


services:
  serv1:
#    image: louislam/uptime-kuma:latest
    image: repo.local.com/uptime-kuma:1.23.16
    container_name: uptime-kuma
    volumes:
      - /home/data/uptime-kuma/data:/app/data
#    environment:
#      TZ: Asia/Shanghai
#    privileged: true
#    devices:
#直通显卡给 Docker 容器，用于硬解
#      - /dev/dri:/dev/dri
#    extra_hosts:
#      "api.themoviedb.org": "13.224.161.90"
    ports:
      - 8099:3001
    restart:
      unless-stopped

