version: '3.3'
services:
  serv1:
#    image: neosmemo/memos:latest
    image: repo.local.com/memos:0.14.4
    container_name: memos
    volumes:
      - /home/data/memos:/var/opt/memos
    ports:
      - 5230:5230
    restart:
      unless-stopped

