version: '3.3'
services:
  
  adguard:
    image: repo.local.com/adguard:20230808
    container_name: adguard
    volumes:
      - /home/data/adguard/workdir:/opt/adguardhome/work
      - /home/data/adguard/confdir:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3002:3002"
      - "3000:3000"
    restart:
      always
    

