version: '3.3'
services:
  serv1:
    image: repo.local.com/world-monitor:2.5.24
#    image: repo.local.com/ssh-alpine:1.0
    container_name: worldmonitor
#    volumes:
#      - /home/data/jizhang:/html
    environment:
      ROOT_PASSWORD: admin   #如不配置默认为admin

#    privileged: true
    ports:
      - 2229:22
      - 8029:80
    restart:
      unless-stopped

