version: '3.3'
services:
  serv1:
#    image: docker.1panel.live/searxng/searxng
    image: repo.local.com/searxng
    container_name: searxng
    volumes:
      - /home/data/searxng/data:/data
    environment:
      SEARXNG_SETTINGS_PATH: /data/setting.yml
#    privileged: true
#    devices:
#直通显卡给 Docker 容器，用于硬解
#      - /dev/dri:/dev/dri
#    extra_hosts:
#      "api.themoviedb.org": "13.224.161.90"
    ports:
      - 8090:8080
    restart:
      unless-stopped

