version: '3.3'
services:
  elk:
    #image: sebp/elk
    image: sanwenjing/elk:8.3.3
    container_name: elk01
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    restart:
      always
    environment:
      ES_MIN_MEM: 128m
      ES_MAX_MEM: 1024m
