version: '3.3'
services:
  serv1:
    image: repo.local.com/openclaw-alpine:2026.3.2_env
    container_name: openclaw-alpine1
    environment:
      ROOT_PASSWORD: admin
      MODEL_BASE_URL: https://your_api/v1
      MODEL_API_KEY: ${MODEL_API_KEY:-}
      MODEL_NAME: ${MODEL_NAME:-}
      FEISHU_APP_ID: ${FEISHU_APP_ID:-}
      FEISHU_APP_SECRET: ${FEISHU_APP_SECRET:-}
      GATEWAY_TOKEN: ${GATEWAY_TOKEN:-}
    ports:
      - 2223:22
    restart: unless-stopped
