version: "3.3"

services:
  docker-portainer:
    container_name: serv-portainer
    #image: sanwenjing/portainer:2.0.1
    image: sanwenjing/portainer:2.0.1
    restart: always
    network_mode: bridge
    ports:
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
