version: '3.3'

#networks:
#  blinko-network:
#    driver: bridge


services:
  serv1:
#    image: deluan/navidrome:latest
    image: repo.local.com/navidrome:0.55.1
    container_name: navidrome
    user: 0:0 # should be owner of volumes
    volumes:
      - /home/data/navidrome/data:/data
      - /home/data/navidrome/music:/music:ro     #存放自己的音乐文件
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    ports:
      - 4533:4533
    restart:
      unless-stopped

  music_tag_web:
#    image: xhongc/music_tag_web:latest
    image: repo.local.com/music_tag_web:2.3.7
    container_name: music_tag_web
    ports:
      - "8002:8001"                #左侧的8002可以自定义
    volumes:
      - /home/data/navidrome/music:/app/media    #存放自己的音乐文件
      - /home/data/navidrome/tag/data:/app/data
    restart: unless-stopped

