version: '3.3'
services:
  serv1:
#    image: docker.1ms.run/stirlingtools/stirling-pdf
    image: repo.local.com/stirling-pdf
    container_name: stirling-pdf
    volumes:
      - /home/data/stirling-pdf/config:/config
#    environment:
#      TZ: Asia/Shanghai
#    privileged: true
#    devices:
#直通显卡给 Docker 容器，用于硬解
#      - /dev/dri:/dev/dri
#    extra_hosts:
#      "api.themoviedb.org": "13.224.161.90"
    ports:
      - 8098:8080
    restart:
      unless-stopped

