version: '3.3'

#networks:
#  blinko-network:
#    driver: bridge


services:
  serv1:
#    image: qingfeng2336/it-tools:latest
    image: repo.local.com/it-tools
    container_name: it-tools
#   volumes:
#      - /home/data/jellyfin/config:/config
    environment:
      TZ: Asia/Shanghai
      PUID: 0
      PGID: 0
#    privileged: true
#    devices:
#直通显卡给 Docker 容器，用于硬解
#      - /dev/dri:/dev/dri
#    extra_hosts:
#      "api.themoviedb.org": "13.224.161.90"
#    network_mode: host
#    command: ['bash','-c','/app/conf/server.toml']
    ports:
      - 8092:80
    restart:
      unless-stopped

